modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "multiworld"
version = "1.4.2"
displayName = "WesterosCraft Multiworld"
authors = "Isaiah"
description = '''
Adds support for teleporting to & creating multiple worlds.
'''
#logoFile = ""

[[dependencies.multiworld]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiworld]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"