modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "multiworld"
version = "1.4.1"
displayName = "Multiworld"
authors = "Isaiah"
description = '''
Adds support for teleporting to & creating multiple worlds.
'''
#logoFile = ""

[[dependencies.multiworld]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiworld]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"